### ISSUE TITLE
Implement autogeneration of documentation

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#10]
Look into various methods for auto generating documentation such as Sphinx, and implement.

[Options](https://medium.com/@peterkong/comparison-of-python-documentation-generators-660203ca3804)

AC:
Docstrings are automatically converted into documentation by something such as a github action.

**Comment by milen-sage** [comment]
I think this is in good state. @andrewelamb could you link the example you had?

**Comment by andrewelamb** [comment]
@milen-sage [docs](https://sage-bionetworks.github.io/schematic_db/)
