### ISSUE TITLE
shematic_db: simplify method call for Synapse table update

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/schematic_db#114]
AC:
- SynapseDatabase.upsert_table_rows: instead of taking primary key uses the table annotation
- SynapseDatabase._upsert_table_rows: takes a table Synapse id and the primary key

@andrewelamb could you link the relevant functions to upsert Synapse table and construct primary key as we chatted with @GiaJordan?

**Comment by andrewelamb** [comment]
[get_key_attribute](https://github.com/Sage-Bionetworks/schematic_db/blob/develop/schematic_db/schema/schema.py#L60)
[upsert_table_rows](https://github.com/Sage-Bionetworks/schematic_db/blob/develop/schematic_db/rdb/synapse_database.py#L331)
