### ISSUE TITLE
Uploading the same manifest twice duplicates rows

### ISSUE THREAD

**Issue by GiaJordan** [Sage-Bionetworks/schematic_db#129]
**Describe the bug**
When a manifest is uploaded with the `upsert` functionality twice, the rows are duplicated instead of detecting that the rows are already in the table.

**To Reproduce**

1. use `upsert_table_rows` to upload manifest as table
2. upload manifest again
3. There are two copies of every manifest row

Alternatively, on shcematic dev branch

1. use `schematic submit ... -tm upsert` to upsert a manifest into a table
2. call the command again on the same table
3. rows are duplicated

**Expected behavior**
Rows that already exist in the table are not uploaded to the table again

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 - schematic-db `v0.0.4`
 - windows 10
 - dev branch of schematic

**Additional context**

**Comment by GiaJordan** [comment]
@milen-sage

**Comment by andrewelamb** [comment]
@GiaJordan Could you provide a reprex? I tried doing this on one of my test tables and got the same table out of it(ie. the table didn't change after uploading it a second time)

**Comment by andrewelamb** [comment]
It seems I can't recreate this using @GiaJordan table and csv:

```
    def test_upsert_table_rows2(
        self,
        secrets_dict: dict,
        data_directory: str,
    ) -> None:
        """Testing for SynapseDatabase.upsert_table_rows()"""
        import logging
        obj = SynapseDatabase(
            SynapseConfig(
                project_id="syn27042964",
                username=secrets_dict["synapse"]["username"],
                auth_token=secrets_dict["synapse"]["auth_token"],
            )
        )
        table_name = "patient_synapse_storage_manifest_table"
        upsert_table = pd.read_csv(f"{data_directory}/upsert_test.csv")
        logging.warning(upsert_table)
​
        res = obj.query_table(table_name)
        logging.warning(res)
        obj.upsert_table_rows(table_name, upsert_table)
        res = obj.query_table(table_name)
        logging.warning(res)
​
        assert False
```

and got this result: 

```
WARNING  root:test_synapse_database.py:321    Patient_id     Sex  Year of Birth  ... Component Cancer Type  Family History
0           5    Male           1954  ...   Patient         NaN             NaN
1           6  Female           1955  ...   Patient         NaN             NaN
2           7    Male           1956  ...   Patient         NaN             NaN
3           8  Female           1957  ...   Patient         NaN             NaN

[4 rows x 7 columns]
WARNING  root:test_synapse_database.py:324    Patient_id     Sex  ...                                  Uuid entityId
0           5    Male  ...  3292b4ff-8bf7-498d-a6c0-8d4a643104e5      NaN
1           6  Female  ...  4c7e534a-4cfb-4102-b7d1-c01c9aeb95b5      NaN
2           7    Male  ...  73cc1244-1dcd-4f6d-b4ab-b055f339ccf4      NaN
3           8  Female  ...  93d0ccd4-d8ad-459c-a244-e9e89d29b704      NaN

[4 rows x 9 columns]
WARNING  root:test_synapse_database.py:327    Patient_id     Sex  ...                                  Uuid entityId
0           5    Male  ...  3292b4ff-8bf7-498d-a6c0-8d4a643104e5      NaN
1           6  Female  ...  4c7e534a-4cfb-4102-b7d1-c01c9aeb95b5      NaN
2           7    Male  ...  73cc1244-1dcd-4f6d-b4ab-b055f339ccf4      NaN
3           8  Female  ...  93d0ccd4-d8ad-459c-a244-e9e89d29b704      NaN

[4 rows x 9 columns]
```

**Comment by GiaJordan** [comment]
@mialy-defelice on
https://github.com/Sage-Bionetworks/schematic/tree/develop-schematicDB-incorp

**Comment by mialy-defelice** [comment]
@andrewelamb @GiaJordan 

I remember you saying I need to also install schematic_db. I assumed this was a pip install but I see now this is not the case. How should I be using schematic_db in conjunction with Schematic?

**Comment by andrewelamb** [comment]
It's in [PyPI](https://pypi.org/project/schematic-db/), so it should be installable through pip. I was assuming @GiaJordan had gotten it to install.

**Comment by mialy-defelice** [comment]
Oh okay, that's what I thought...I couldn't find it before, but of course I find it after I ask. Thanks!

**Comment by andrewelamb** [comment]
If there are any issues installing please let me know :)

**Comment by GiaJordan** [comment]
@mialy-defelice yes! Version 0.0.6 is the one with the dependency updates I made so it should be the easiest to use. You'll want the `synapse` extras

**Comment by GiaJordan** [comment]
> WARNING  root:test_synapse_database.py:321    Patient_id     Sex  Year of Birth  ... Component Cancer Type  Family History
> 0           5    Male           1954  ...   Patient         NaN             NaN
> 1           6  Female           1955  ...   Patient         NaN             NaN
> 2           7    Male           1956  ...   Patient         NaN             NaN
> 3           8  Female           1957  ...   Patient         NaN             NaN
> 
> [4 rows x 7 columns]
> WARNING  root:test_synapse_database.py:324    Patient_id     Sex  ...                                  Uuid entityId
> 0           5    Male  ...  3292b4ff-8bf7-498d-a6c0-8d4a643104e5      NaN
> 1           6  Female  ...  4c7e534a-4cfb-4102-b7d1-c01c9aeb95b5      NaN
> 2           7    Male  ...  73cc1244-1dcd-4f6d-b4ab-b055f339ccf4      NaN
> 3           8  Female  ...  93d0ccd4-d8ad-459c-a244-e9e89d29b704      NaN
> 
> [4 rows x 9 columns]
> WARNING  root:test_synapse_database.py:327    Patient_id     Sex  ...                                  Uuid entityId
> 0           5    Male  ...  3292b4ff-8bf7-498d-a6c0-8d4a643104e5      NaN
> 1           6  Female  ...  4c7e534a-4cfb-4102-b7d1-c01c9aeb95b5      NaN
> 2           7    Male  ...  73cc1244-1dcd-4f6d-b4ab-b055f339ccf4      NaN
> 3           8  Female  ...  93d0ccd4-d8ad-459c-a244-e9e89d29b704      NaN
> 
> [4 rows x 9 columns]
> ```

@andrewelamb where in the code were these warnings generated? For the 2nd upload, at the final `syn.store`, `data` is as below
```
data
  Patient_id     Sex Year of Birth Diagnosis Component Cancer Type Family History                                  Uuid entityId  ROW_ID  ROW_VERSION
0          5    Male          1954   Healthy   Patient                             e47dd52a-0183-4e7f-bf1f-39a9c8e44db0              NaN          NaN
1          6  Female          1955   Healthy   Patient                             c79f7e0e-2997-4bee-8830-55b7d1aebb0d              NaN          NaN
2          7    Male          1956   Healthy   Patient                             6f0641f7-15d0-42ac-9501-4e29fba48fb6              NaN          NaN
3          8  Female          1957   Healthy   Patient                             abbda037-af9e-4b4b-a263-278a2c4bb83e              NaN          NaN
```
but the resulting table on synapse still has 8 rows instead of 4

**Comment by andrewelamb** [comment]
@GiaJordan I uploaded the new the above test [here.](https://github.com/Sage-Bionetworks/schematic_db/blob/bugfix-129-upsert/tests/test_synapse_database.py#L305)

I'm still not able to reproduce the additional rows.

**Comment by GiaJordan** [comment]
This has been resolved. It was caused by the temporary fix we put in schematic while we waited for the synapsePythonClient to be updated. I've submitted a PR to rectify
cc: @milen-sage
