### ISSUE TITLE
Add update_all_tables() method to RDB.py

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#14]
Eventually this will need a schema object, or and endpoint that returns something like DBObjectConfig(preferably in the order the tables should be made). For now this could take in a list[DBObjectConfig].
AC:
Add update_all_tables() method to RDB class
iterates over list[DBObjectConfig] calling update_database_table

**Comment by milen-sage** [comment]
Related to #2.
