### ISSUE TITLE
Use pytest fixtures for setup and teardown

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#16]
Most of the testing uses either a synapse object or a database. 

If a table gets added or altered during a test the original state should be reverted back. Currently this happens in the tests themselves, but if a test fails an assertion at any point it will immediately stop. Some tests also have setup in common. 

For this reason the setup and teardown should be moved to pytest fixtures.

AC: 
Setup and teardown code for mysql.py, synapse.py and rdb.py moved into pytest fixtures.

**Comment by milen-sage** [comment]
@andrewelamb I think I saw the testing modules, but could you link them here when you have a chance?

**Comment by andrewelamb** [comment]
@milen-sage Please see the linked PR above.
