### ISSUE TITLE
Create RDB object

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#2]
[See.](https://docs.google.com/document/d/159EwbR1jJ2uRyVPJVBvZ1JPER4RKU8-Z3JeiKktUGFM/edit)

RDB is an object that is composed of a Schema object, and a [RDBType object.](https://github.com/Sage-Bionetworks/schematic_db/issues/1)

AC: RDB object implemented with required methods.

Several methods will need to be added later:
- Delete rows from table
- Drop table
- Update all tables

Will also need to incorporate a Schema object

**Comment by milen-sage** [comment]
@andrewelamb did you have a chance to do a first pass on the RDB class? Feel free to link PRs/commits here.

**Comment by andrewelamb** [comment]
@milen-sage [PR](https://github.com/Sage-Bionetworks/schematic_db/pull/11)
