### ISSUE TITLE
Normalize manifests

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#26]
Manifests will sometimes be denormalized, ie. they will have data from multiple components. Schematic db should assume they will be denormalized and normalize each table.

1. Select the columns that should be there
2. Throw an error if primary keys are missing
3. Remove any duplicates
4. Throw an error if there are duplicated records(same primary keys but differ in other columns)

AC:
Add the code above into a function that mysql.py uses (and other rdb types can use in the future)

**Comment by milen-sage** [comment]
@andrewelamb how is this going, should we plan for sprint 15?

**Comment by andrewelamb** [comment]
@milen-sage Please see the linked PR above.
