### ISSUE TITLE
Implement cascading deletes

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/schematic_db#49]
For rows this will need to be implemented in two places:
- In rdb.MySQL._create_columns, use something like `sa.ForeignKey('customer.id', ondelete='CASCADE')`
- In rdb.Synapse.delete_table rows needs to be filled out
- in synpase.Synapse.update_table_rows would likely need to be recursive in some way

It's possible that delete_table_rows should be removed from the RDB interface s the methods for mysql and synapse will have different signatures.

@milen-sage would we want to implement cascading deletes for whole tables, or just rows?

**Comment by milen-sage** [comment]
Just the rows for now. Implementing for the whole tables would be dangerous; let's see if they are request for that later and we can decide how to handle it.
